title: Jaeden Ng # your name (or website title) here
logo: "/images/profile-pic.png?raw=true" # your photo (or logo) here
description: # your text below (remove <br> elements if you don't need line breaks)
A technologist and creative person who has very keen interest in the interactive marketing and advertising in the digital space. <br><br>
I am currently interested data science, user experience design, experience research & social media marketing.
<br><br>
Some of my hobbies includes photography, arts & design, gaming.
<br><br>
<b>Skills:</b>Data Analysis, Data Visualisation, User Research, Prototyping, Wire-framing, Story-Boarding, Annotation, Usability Testing, Information Architect, User Flows, Project Management
<b>Codes:</b> HTML5, CSS3, Ajax, JavaScript, JQuery, ASP, Java, SQL, Python.
<b>Software:</b> Axure, InVision, Sketch, Omnigraffle, Photoshop, Lightroom, PremierPro, Illustrator, Flash, Dreamweaver, InDesign, 3D Studio Max, Tableau, PowerBI, Excel
  <br><br>
  <a href="https://www.linkedin.com/in/jindeng/" target="_blank">View My LinkedIn Profile</a>
  <br>
  <a href="mailto:jindesignart@hotmail.com">Email Me</a>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
