title: Jaeden Ng # your name (or website title) here
logo: "/images/profile-pic.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  A technologist and creative person who has very keen interest in data science, user experience design, experience research and social media marketing.
  <br><br>
  Some of my hobbies includes photography, DIY stuffs, problem solving, gaming. 
  <br><br>
  <a href="https://www.linkedin.com/in/jindeng/" target="_blank">View Jaeden's <b>LinkedIn</b> Profile</a>
  <br>
  <b>Email:</b> <a href="mailto:jaeden.ng@hotmail.com">jaeden.ng@hotmail.com</a>
  <br><br>
  <b>Skills/Knowledge:</b> Data Analysis, Data Visualisation, User Research, Prototyping, Wire-framing, Story-Boarding, Annotation, Usability Testing, Information Architect, User Flows, Project Management
  <br><br>
  <b>Code:</b> HTML5, CSS3, Ajax, JavaScript, JQuery, ASP, Java, SQL, Python.
  <br><br>
  <b>Software:</b> Tableau, PowerBI, Excel, Axure, InVision, Sketch, Omnigraffle, Photoshop, Lightroom, PremierPro, Illustrator, Flash, Dreamweaver, InDesign, 3D Studio Max
  
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
